---
title: "Guided Tidy Tuesday: gt edition"
author: "Kyla McConnell"
date: "9/29/2021"
output: html_document
---

```{r}
library(tidyverse)
library(gt)
library(scales)

nominees <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-21/nominees.csv')
```

```{r}
colnames(nominees)
```

```{r}
nominees %>% 
  distinct(category)
```

```{r}
summary(nominees$year)
```

## Which shows have won the most awards?
```{r}
nominees %>% 
  filter(type == "Winner") %>% 
  distinct(category, title) %>% 
  count(title) %>% 
  arrange(desc(n))

nominees %>% 
  filter(type == "Winner") %>% 
  distinct(category, title) %>% 
  group_by(title) %>% 
  tally() %>% 
  arrange(desc(n))
```

## Which distributors have won the most awards this year?
```{r}
winners <- nominees %>% 
  filter(type == "Winner" & year == 2021) %>% 
  mutate(distributor = recode(distributor,
    "Apple TV+" = "Apple TV",
    "App Store, Apple TV+" = "Apple TV",
    "HBO Max" = "HBO"
  )) %>% 
  count(distributor) %>% 
  top_n(10) %>% 
  arrange(desc(n))
```

```{r}
winners_gt <- winners %>% 
  gt() %>% 
  tab_header(
    title = md("**2021 Emmy Winners**"),
    subtitle = md("**Top 10 distributors by Emmy wins**")
  ) %>% 
  tab_source_note("Source: TidyTuesday Github") %>% 
  cols_label(
    distributor = "",
    n = ""
  ) %>% 
  data_color(
    columns = n,
    colors = scales::col_numeric(
      palette = c("white", "#63BAAB"),
      domain = NULL
    )
  ) %>% 
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_body(distributor)
  ) 

winners_gt %>% 
gtsave("emmys_distributor2021.png",
       expand = 20)
```


## Costume winners
```{r}
costumes <- nominees %>% 
  filter(str_detect(category, "Costume") & year == 2021) %>% 
  mutate(category = str_remove(category, "Outstanding"),
         category = str_remove(category, "Costumes - 2021"),
         category = str_trim(category)) %>% 
  filter(category %in% c("Period", "Contemporary", "SciFi/Fantasy"))
```

```{r}
costumes %>% 
  distinct(category, type, title, distributor) %>% 
  gt(
    groupname_col = "category"
  ) %>% 
  tab_header(
    title = md("**2021 Emmy Awards for Costume**"),
    subtitle = md("**in the categories Period, Contemporary, and SciFi/Fantasy**")
  ) %>% 
  tab_source_note("Source: TidyTuesday Github") %>% 
  cols_label(
    type = "",
    title = md("**Title**"),
    distributor = md("**Distributor**")
  )
```

